### ISSUE TITLE
Duplicate with debstrap?

### ISSUE THREAD

**Issue by pparent76** [Own-Mailbox/omb#4] opened 2018-03-13 08:18 UTC
I don't really understand how this repo is supposed to work.

It seems to me that many things are duplicated with debstrap, isn't it?

Wouldn't it be better that this repo actually clones and uses debstrap in order to build the docker container?

**Comment by dashohoxha** [comment] 2018-03-13 09:54
Thanks for asking.

The repository **debstrap** is the original one, which is working. I have only added `Vagrantfile` for easy testing with VirtualBox. There are also some small fixes that you have made.

This repository (**docker**) is the one where installation is done in a container. There are some changes in the structure of the installation scripts. Also the image is based on Ubuntu, rather than Debian. Maybe we should switch back to Debian, I am not sure. But again the version of Debian would be different from the original **debstrap** repo, so maybe the scripts would need to fixed anyway.

I have tried my best to keep the new scripts equivalent in function to the old ones, but still there may be some things that need to be fixed. This is why I decided to keep them separate and not mixing with each-other. 

So, yes, this repo is a duplicate of **debstrap** in functionality, however it is the new version of it, and it still needs to be tested, fixed, improved, etc.

@giorgos314

**Comment by pparent76** [comment] 2018-03-13 10:07
The problem is that this way, when we make a modification in debstrap we should also make it in here. And we are never sure that the 2 versions are really equivalant.

I think it would be better to base this on debstrap and have only a set of patch, needed for docker, so that when we change debstrap it automatically have impact on the docker container.

**Comment by dashohoxha** [comment] 2018-03-13 10:58
**debstrap** is the old/legacy version. We are keeping it around just because we know that it works. New development should be done here. For small fixes or patches it is not a problem to apply to both of them.

> I seem to remember that on early versions patch needed for docker against debstrap where very light.

You are right, it worked that way. But it has changed. The way forward is to add to this repo (to the new one) a Vagrantfile, so that it can be installed easily on a VirtualBox machine as well. Maybe we can also add a script (similar to `main.sh` in the old repo) that can do the installation on a brand new debian installation.

**Comment by pparent76** [comment] 2018-03-13 11:34
For me we cannot consider debstrap as legacy. Because we need to be able to install it directly on a debian machine, like raspberry pi or Own-Mailbox hardware, without docker layer.

Always using docker, to me would be an unnecessary sources of risk of security venerabilities,  even more since docker implies a special way of handling iptables.

**Comment by pparent76** [comment] 2018-03-13 11:52
Other reasons why I don't think making docker a core component of own-mailbox is not a good idea are:

*It's not packaged in official debian repositries
*It's a semi-free software project (it has an "open-source" community edition, and a non-free edition), the philosophy of this software does not seem to me as fully compatible with the own-mailbox project.

**Comment by dashohoxha** [comment] 2018-03-13 11:52
> For me we cannot consider debstrap as legacy. Because we need to be able to install own-mailbox, directly on a debian machine, like raspberry pi or Own-Mailbox hardware, without docker layer.

I agree. Let's add this feature (installing directly on a debian machine) on this repository (#5). But let's keep **debstrap** untouched.

Would you like me to add this feature, or you can add it yourself? Or maybe @giorgos314 would like to give it a try?

**Comment by pparent76** [comment] 2018-03-13 14:39
I know that debstrap is not that clean, it should clearly be improved a lot and it could be a task for Gsoc. But when developing own-mailbox, it would be good to be able to do it without having to think, or keep in mind how docker or vagrant works. Even I have few experience with it, and I really do not want to have to make research about it, or have constantly mind space allocated to keep in mind  why things in Own-mailbox are done the way they are because of docker or vagrant way to work. Especially, if the final users won't use vagrant or docker in a real use-case where they use it on a small box at home.

I really have a hard time understanding how this repo works.

It seems to me that old docker scripts where good, ( https://github.com/Own-Mailbox/debstrap/commit/006c10a5102211d3c842e8218a69890f12a21d46 ), even though I think it is a good idea to move docker scripts, and vagrant scripts in a separate repo, that would clone debstrap in the installation process.

Also I'm not sure if this repo is currently fully working?

What do you think?

**Comment by dashohoxha** [comment] 2018-03-13 15:43
Pierre, just because we are not familiar with docker, or don't like docker, or don't trust docker, we should not restrict the preferences of other people. There may be people who prefer to use docker (for example I am one of them). So, let's not be restrictive.

To know how this repo works you should know how https://github.com/docker-scripts/ds works. Don't worry, it is much easier and intuitive than you think. For the time being, you can have a look at this script: https://github.com/Own-Mailbox/docker/blob/master/cmd/config.sh (It is the equivalent of `main.sh` in the old installation scripts.)

Since you are not familiar with docker-scripts, let me do task #5. For the time being I am a bit sick and my brain does not work efficiently, but I will do it soon. It should be much easier than you think.

> Also I'm not sure if this repo is currently fully working?

We have already discussed that it is not fully functional and it needs to be fixed. Part of the problem is the migration from the debian to ubuntu (or from old debian to the latest one, if we switch back to debian again).

**Comment by pparent76** [comment] 2018-03-13 17:32
Thank's for your answer,

> So, let's not be restrictive.

I do agree, and I really like the idea that we can run own-mailbox in docker vagrant or other. I do not want  to get rid of docker at all, which I really to like in order to make tests. What I am discussing  here is whether we should rewrite all own-mailbox scripts with docker in mind, and adapt all core scripts for docker since the beginning, and get rid of the possibility to develop Own-Mailbox without using docker.

I'm discussing that because you proposed to replace Own-Mailbox main repository by one called "docker". I may have missed something.

> we should not restrict the preferences of other people
I completely agree, that's why I would like that anyone be able to develop on Own-Mailbox whether, he likes docker, vagrant or not, and weather he knows how to use it or not.  

>For the time being I am a bit sick and my brain does not work efficiently,
Ok take your time no worries.

**Comment by dashohoxha** [comment] 2018-03-13 20:17
> you proposed to replace Own-Mailbox main repository by one called "docker"

The name of this repository (`docker`) is wrong. It should be renamed to something else, like `omb` or `server` or `ombserver`. Let me know which one you think is more appropriate and I will fix it.

**Comment by dashohoxha** [comment] 2018-03-14 01:34
I renamed it to `omb`, to avoid any confusions. Later we can change it to something else if needed.

**Comment by pparent76** [comment] 2018-03-14 09:11
Ok but that's not only a problem of name, I think:

-We should separate docker scripts and vagrant scripts, from omb core scripts (at least in a different folder)
-Doing a complete rewrite is very conter-intuitive for me. I'm more used to step by step improvement while always keeping it working and with no regression. Especially because for me a complete rewrite, requires to have in mind a complete knowledge of how the old version works and/or have a lot of time for developing and testing, which neither of us seem to have right now.

**Comment by pparent76** [comment] 2018-03-14 09:20
Also:
-Why is this docker container based on Ubuntu, rather than debian?
-We should also keep in mind that omb core scripts must remain compatible with Raspbian, since it has been chosen as a target of the project.

**Comment by giorgos314** [comment] 2018-03-14 17:50
Since the project is under the Debian umbrella organisation, wouldn't it be weird to work with Ubuntu? Or (if the proposal if accepted of course) am I going to work with a different repo?

**Comment by pparent76** [comment] 2018-03-14 22:47
@dashohoxha

As you can see I could not resist reworking a little bit on debstrap. I pushed it by mistake, because I initially intended to keep it for myself at first. But anyways, I cannot hide, that I am personally kind of attached to debstrap (even though we could change name), and I have a hard time getting the point of giving it up instead of improving it. 

Also, as the initiator of the project, I'm attached to some core features. In my mind being able to install omb on a small hardware running debian is not a bonus feature of having a docker container. Docker is the bonus feature.  Install omb on a small hardware running debian is the core feature.

I understand that you made some work, for this new repository, even though I did not get it until soon. And I really don't want to deprivate you from it, and I understand that you can feel attached to it. I don't want you to feel bad, if we are to keep working together. 

Maybe we can find a solution in between? Can you tell us your feelings about that? What is important to you?

**Comment by dashohoxha** [comment] 2018-04-04 10:53
> Since the project is under the Debian umbrella organisation, wouldn't it be weird to work with Ubuntu? Or (if the proposal if accepted of course) am I going to work with a different repo?

I tried both Ubuntu and Debian, and found Ubuntu easier to work with and more convenient. This was before even thinking making a GSoC project under umbrella of Debian.

I have nothing against the Debian, so you are free to switch it to Debian. See #9.

**Comment by dashohoxha** [comment] 2018-04-04 12:28
> I think a complete rewrite, requires to have in mind a complete knowledge of how the old version works and/or have a lot of time for developing and testing, which neither of us seem to have right now

This is a good point. We need to have a complete and documented knowledge of how the server is built and how it works:
 - what are the services that need to be installed
 - how to install them (what packages or code to install)
 - what are the necessary configurations of each service and how to do them
 - how to test that each service have been installed and works correctly
 - how to debug and fix them in case they are not working as expected, etc.

The documentation should have enough details so that anyone can build a new server from scratch.

It may take some time, but we don't have to do it right now and quickly. @giorgos314 can help us for this too.

I can show some examples of such documentation of projects that I have done on the past (sorry for boosting myself):
 - https://www.researchgate.net/publication/321686187_Managing_Internet_Connections_With_PPPoE_Mikrotik_and_Radius
 - https://www.researchgate.net/publication/317181126_Building_a_Gateway_Server
 - https://www.researchgate.net/publication/317180708_Managing_HotSpot_Clients_With_FreeRadius
 - https://www.researchgate.net/publication/315829222_Managing_Internet_Connections_With_PPPoE_Mikrotik_and_Radius

**Comment by dashohoxha** [comment] 2018-04-04 13:59
> I'm more used to step by step improvement while always keeping it working and with no regression.

This is the most normal way of development, I work like this too. 
However this also needs to test after each step that everything is working and there are no regressions. Sometimes it is easy to do the testing manually, sometimes it may be time consuming and tedious. Usually it is nice to have automated testing, although it is not an absolute requirement. See #12

**Comment by dashohoxha** [comment] 2018-04-04 14:16
> Doing a complete rewrite is very conter-intuitive for me.

I did not do a complete rewrite. I did it in step-by-step small changes. A lot of such small changes maybe give you the impression of a big rewrite, which is not the case.
If it does not work, the problem is with the upgrade from debian:jessie to debian:stretch (or from debian:jessie to ubuntu:xenial).

**Comment by dashohoxha** [comment] 2018-04-04 14:17
> Also, as the initiator of the project, I'm attached to some core features. In my mind install omb on a small hardware running debian is the core feature, not a bonus feature of a docker container.

I have never been against this feature or against installing it directly on RaspberyPi.

**Comment by dashohoxha** [comment] 2018-04-04 14:30
I never doubt that you are the initiator and the leader of this project.
I only try to help the project go on the right path and direction.
Having about 20 years of work experience (excuse me for being a boaster) I have learned some lessons from my mistakes in server management, software development, project management, etc.
Sometimes I see you making the mistakes that I did when I was young, and I want to help this project avoid such mistakes.
This is my motivation. I hope that you are not embarrassed from my interference. But if you are, I can also get out of the way, so that you can run the project the way that you think is best.

**Closed by dashohoxha** 2018-04-04 14:30 UTC
